version: "2.3"
services:
  mariadb:
    image: crocodile2u/mariadb-rocks:10.4
    container_name: mariadb
    dns_search: williamdes.local
    hostname: mariadb.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    networks:
      williamdeslocal:
        aliases:
          - mariadb.williamdes.local
          - mariadb104.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mariadb-server:/var/lib/mysql"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
      - "/mnt/Dev/!OSS/public/mysqld.cnf:/etc/mysql/mariadb.conf.d/ssl.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    ports:
      - "3306:3306"

  mariadb105:
    image: mariadb:10.5
    container_name: mariadb105
    dns_search: williamdes.local
    hostname: mariadb105.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    networks:
      williamdeslocal:
        aliases:
          - mariadb105.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mariadb105-server:/var/lib/mysql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

  mariadb102:
    image: mariadb:10.2
    container_name: mariadb102
    dns_search: williamdes.local
    hostname: mariadb102.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    networks:
      williamdeslocal:
        aliases:
          - mariadb102.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mariadb102-server:/var/lib/mysql"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

  mysql5726:
    image: mysql:5.7.26
    container_name: mysql5726
    dns_search: williamdes.local
    hostname: mysql5726.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    networks:
      williamdeslocal:
        aliases:
          - mysql5726.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mysql-server:/var/lib/mysql"
      - "./servers/php-custom.d:/etc/php-custom.d"
    ports:
      - "4406:3306"

  mysql5717:
    image: mysql:5.7.17
    container_name: mysql5717
    dns_search: williamdes.local
    hostname: mysql5717.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    networks:
      williamdeslocal:
        aliases:
          - mysql5717.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mysql-5726-server:/var/lib/mysql"
      - "./servers/php-custom.d:/etc/php-custom.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    ports:
      - "4407:3306"

  mysql578:
    image: mysql:5.7.8
    container_name: mysql578
    dns_search: williamdes.local
    hostname: mysql578.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    networks:
      williamdeslocal:
        aliases:
          - mysql578.williamdes.local
    volumes:
      - "/mnt/Dev/!OSS/servers/mysql-578-server:/var/lib/mysql"
      - "./servers/php-custom.d:/etc/php-custom.d"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

  nginx:
    image: nginx
    container_name: nginx
    dns_search: williamdes.local
    hostname: nginx.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 100m
    volumes:
      - "/mnt/Dev/!OSS/servers/nginx/:/etc/nginx"
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "/var/log/containers/nginx:/var/log/nginx"
    networks:
      williamdeslocal:
        aliases:
          - nginx.williamdes.local
          - proxy1.local
          - proxy2.local
          - 8.0.local
          - pma.selenium.local
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"

  #  varnish:
  #    image: "varnish:latest"
  #    container_name: varnish
  #    dns_search: williamdes.local
  #    hostname: varnish.williamdes.local
  #    domainname: williamdes.local
  #    restart: on-failure:2
  #    mem_limit: 100m
  #    tmpfs:
  #      - /var/lib/varnish:exec
  #    volumes:
  #      - "/mnt/Dev/!OSS/servers/varnish/:/etc/varnish"
  #    networks:
  #      williamdeslocal:
  #        aliases:
  #          - varnish.williamdes.local
  #    ports:
  #      - "800:80"
  #      - "4430:443"

  pmatest:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pmatest
    dns_search: williamdes.local
    hostname: pmatest.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 100m
    networks:
      williamdeslocal:
        aliases:
          - pmatest.williamdes.local
    env_file:
      - ./pma.env
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    ports:
      - "500:80"

  haproxy:
    image: "haproxy:latest"
    container_name: haproxy
    dns_search: williamdes.local
    hostname: haproxy.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 100m
    tmpfs:
      - /var/lib/haproxy:exec
    volumes:
      - "/mnt/Dev/!OSS/servers/haproxy/:/usr/local/etc/haproxy"
    networks:
      williamdeslocal:
        aliases:
          - haproxy.williamdes.local
    ports:
      - "900:80"
      - "4431:443"

  #  haproxy:
  #    image: "haproxy:latest"
  #    container_name: haproxy
  #    dns_search: williamdes.local
  #    hostname: haproxy.williamdes.local
  #    domainname: williamdes.local
  #    restart: on-failure:2
  #    mem_limit: 100m
  #    tmpfs:
  #      - /var/lib/haproxy:exec
  #    volumes:
  #      - "/mnt/Dev/!OSS/servers/haproxy/:/usr/local/etc/haproxy"
  #    networks:
  #      williamdeslocal:
  #        aliases:
  #          - haproxy.williamdes.local
  #    ports:
  #      - "900:80"
  #      - "4431:443"

  phpfpm53:
    image: devilbox/php-fpm-5.3:latest
    container_name: phpfpm53
    dns_search: williamdes.local
    hostname: 5.3.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 1g
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 5.3.williamdes.local
          - pma.5.3.local
          - 5.3.local

  phpfpm55:
    image: devilbox/php-fpm:5.5-mods
    container_name: phpfpm55
    dns_search: williamdes.local
    hostname: 5.5.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 1g
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 5.5.williamdes.local
          - pma.5.5.local
          - 5.5.local

  phpfpm70:
    image: devilbox/php-fpm:7.0-mods
    container_name: phpfpm70
    dns_search: williamdes.local
    hostname: 7.0.williamdes.local
    domainname: williamdes.local
    restart: on-failure:0
    mem_limit: 600m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 7.0.williamdes.local
          - pma.7.0.local
          - 7.0.local

  phpfpm71:
    image: devilbox/php-fpm:7.1-mods
    container_name: phpfpm71
    dns_search: williamdes.local
    hostname: 7.1.williamdes.local
    domainname: williamdes.local
    restart: on-failure:1
    mem_limit: 600m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 7.1.williamdes.local
          - pma.7.1.local
          - 7.1.local

  phpfpm72:
    image: devilbox/php-fpm:7.2-mods
    container_name: phpfpm72
    dns_search: williamdes.local
    hostname: 7.2.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 600m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 7.2.williamdes.local
          - pma.7.2.local
          - 7.2.local

  phpfpm73:
    image: devilbox/php-fpm:7.3-mods
    container_name: phpfpm73
    dns_search: williamdes.local
    hostname: 7.3.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 600m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 7.3.williamdes.local
          - pma.7.3.local
          - 7.3.local

  phpfpm74:
    image: devilbox/php-fpm:7.4-work
    container_name: phpfpm74
    dns_search: williamdes.local
    hostname: 7.4.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 600m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 7.4.williamdes.local
          - pma.7.4.local
          - 7.4.local

  phpfpm80:
    image: devilbox/php-fpm:8.0-work
    container_name: phpfpm80
    dns_search: williamdes.local
    hostname: 8.0.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 300m
    working_dir: /mnt/Dev
    volumes:
      - "/dev/log:/dev/log"
      - "/mnt/Dev:/mnt/Dev"
      - "./servers/php-custom.d:/etc/php-custom.d"
      - "/mnt/Dev/!OSS/public/ssl/:/etc/db-certs/"
    networks:
      williamdeslocal:
        aliases:
          - 8.0.williamdes.local
          - pma.8.0.local
          - 8.0.local

  #mysql55:
  #image: mysql:5.5
  #container_name: mysql55
  #dns_search: williamdes.local
  #hostname: mysql5.5.williamdes.local
  #domainname: williamdes.local
  #restart: on-failure:2
  #mem_limit: 300m
  #environment:
  #- MYSQL_ROOT_PASSWORD=public
  #- MYSQL_DATABASE=public
  #- MYSQL_USER=public
  #- MYSQL_PASSWORD=public
  #volumes:
  #- "./servers/php-custom.d:/etc/php-custom.d"
  #networks:
  #williamdeslocal:
  #aliases:
  #- mysql5.5.williamdes.local
  #- mysql5.5.local

  #perconadb56:
  #image: percona:5.6
  #container_name: perconadb56
  #dns_search: williamdes.local
  #hostname: perconadb5.6.williamdes.local
  #domainname: williamdes.local
  #restart: on-failure:2
  #mem_limit: 300m
  #environment:
  #- MYSQL_ROOT_PASSWORD=public
  #- MYSQL_DATABASE=public
  #- MYSQL_USER=public
  #- MYSQL_PASSWORD=public
  #volumes:
  #- "./servers/php-custom.d:/etc/php-custom.d"
  #networks:
  #williamdeslocal:
  #aliases:
  #- perconadb5.6.williamdes.local
  #- perconadb5.6.local

  mysql80:
    image: "mysql:8.0"
    container_name: mysql80
    dns_search: williamdes.local
    hostname: mysql80.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    networks:
      williamdeslocal:
        aliases:
          - mysql80.williamdes.local
          - mysql80.local

  mysql800:
    image: "mysql:8.0"
    container_name: mysql800
    dns_search: williamdes.local
    hostname: mysql800.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    networks:
      williamdeslocal:
        aliases:
          - mysql800.williamdes.local
          - mysql800.local

  mysql8011:
    image: "mysql:8.0.11"
    container_name: mysql8011
    dns_search: williamdes.local
    hostname: mysql8011.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    networks:
      williamdeslocal:
        aliases:
          - mysql8011.williamdes.local
          - mysql8011.local

  mysql803:
    image: "mysql:8.0.3"
    container_name: mysql803
    dns_search: williamdes.local
    hostname: mysql803.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public
    networks:
      williamdeslocal:
        aliases:
          - mysql803.williamdes.local
          - mysql803.local

  mysql-primary:
    image: "bitnami/mysql:8.0"
    ports:
      - "3306"
    volumes:
      - "mysql_primary_data:/bitnami/mysql/data"
    networks:
      williamdeslocal:
        aliases:
          - mysql-primary.williamdes.local
          - mysql-primary
          - mysql-primary.local
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=sys
      - MYSQL_DATABASE=system
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=password

  mysql-first-replica:
    image: "bitnami/mysql:8.0"
    ports:
      - "3306"
    depends_on:
      - mysql-primary
    networks:
      williamdeslocal:
        aliases:
          - mysql-first-replica.williamdes.local
          - mysql-first-replica
          - mysql-first-replica.local
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_USER=sys
      - MYSQL_DATABASE=system
      - MYSQL_MASTER_HOST=mysql-primary.williamdes.local
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=yes

#  proxy-sql:
#    image: proxysql/proxysql
#    container_name: proxy-sql
#    dns_search: williamdes.local
#    hostname: proxy-sql.williamdes.local
#    domainname: williamdes.local
#    ports:
#      - "16032:6032"
#      - "16033:6033"
#      - "16034:6080"
#    networks:
#      williamdeslocal:
#        aliases:
#          - proxy-sql.williamdes.local
#          - proxy-sql
#          - proxy-sql.local
#    volumes:
#      - "/mnt/Dev/!OSS/proxysql.cnf:/etc/proxysql.cnf"

  selenium-hub-mysql57:
    container_name: selenium-hub-mysql57
    dns_search: williamdes.local
    hostname: selenium-hub-mysql57.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    image: mysql:5.7
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    tmpfs:
      - /var/lib/mysql
      - /tmp
    networks:
      williamdeslocal:
        aliases:
          - selenium-hub-mysql57.williamdes.local
          - selenium-hub-mysql57
          - selenium-hub-mysql57.local
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

  selenium-hub-mariadb102:
    container_name: selenium-hub-mariadb102
    dns_search: williamdes.local
    hostname: selenium-hub-mariadb102.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    image: mariadb:10.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-upublic", "-ppublic"]
      interval: 120s
      timeout: 1s
      retries: 3
    tmpfs:
      - /var/lib/mysql
      - /tmp
    networks:
      williamdeslocal:
        aliases:
          - selenium-hub-mariadb102.williamdes.local
          - selenium-hub-mariadb102
          - selenium-hub-mariadb102.local
    environment:
      - MYSQL_ROOT_PASSWORD=public
      - MYSQL_DATABASE=public
      - MYSQL_USER=public
      - MYSQL_PASSWORD=public

  selenium-hub:
    image: selenium/hub:3.141
    container_name: selenium-hub
    dns_search: williamdes.local
    hostname: selenium-hub.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    networks:
      williamdeslocal:
        aliases:
          - selenium-hub.williamdes.local
          - selenium-hub
          - selenium-hub.local
    ports:
      - "4444:4444"

  chrome1:
    image: selenium/node-chrome:3.141
    container_name: selenium-hub-chrome1
    dns_search: williamdes.local
    hostname: selenium-hub-chrome1.williamdes.local
    domainname: williamdes.local
    restart: on-failure:2
    mem_limit: 500m
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    networks:
      williamdeslocal:
        aliases:
          - selenium-hub-chrome1.williamdes.local
          - selenium-hub-chrome1
          - selenium-hub-chrome1.local
    environment:
      - HUB_HOST=selenium-hub.williamdes.local
      - HUB_PORT=4444

volumes:
  mysql_master_data:
    driver: local

networks:
  williamdeslocal:
    driver: bridge
