version: "3.7"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    command: ["--wait_timeout=28800"]
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mariadb:/etc/mysql/conf.d
      - ./config/server-certs:/etc/certs
    networks:
      legend-data:
        ipv4_address: 10.0.4.123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - PMA_HOST=mariadb
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./config/client-certs:/etc/client-certs
    networks:
      legend-data: null
      legend-web:
        ipv4_address: "10.0.1.151"
volumes:
  mariadb_data:
networks:
  legend-data:
    external:
      name: legend-data
  legend-web:
    external:
      name: legend-web
